### ISSUE TITLE
Switch to yarn?

### ISSUE THREAD

**Issue by monarchwadia** [clairefro/mintbean-cli#8]
`yarn` is much faster at doing `install` then `npm` is
I suggest we switch to yarn
This means we move from using `package-lock.json` to `yarn.lock`

**Comment by clairefro** [comment]
can yarn handle package versioning/publishing to npm?

**Comment by monarchwadia** [comment]
yes! https://classic.yarnpkg.com/en/docs/cli/publish/

**Comment by monarchwadia** [comment]
Not done yet because package-lock.json is still there.
We should delete package-lock.json.

Do we want to switch to yarn for all the templates?

**Comment by clairefro** [comment]
> Not done yet because package-lock.json is still there.
> We should delete package-lock.json.
> 
> Do we want to switch to yarn for all the templates?

Would we need to include `yarn` as a dev dependency in templates if we force it's usage?

**Comment by KmBarnett** [comment]
no I like the current option of allowing the user to chose but we should see if they even have yarn set up
